apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: exercises
  name: ping-pong-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
