apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: the-project-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
